### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ilxplay** [jojommeke/ADHDO#1]
**Describe the bug**
Approximately the half of the screen is just white 

 - Browser Google
 
![Screenshot 2024-10-17 172446](https://github.com/user-attachments/assets/08cc95d8-62d5-4c84-9907-55002923d9d9)

**Comment by tectrixdev** [comment]
I thought it was just me, if you look into inspect element the html class is not filling the whole screen for some reason, will fix

**Comment by tectrixdev** [comment]
Fixed with [de98c7e567809fd9e12bb48b14f04454d2e68752](https://github.com/jojommeke/ADHDO/commit/de98c7e567809fd9e12bb48b14f04454d2e68752)

**Comment by tectrixdev** [comment]
mobile layout still a bit broken though, will fix later
